### ISSUE TITLE
微信支付中能否把刷卡支付加入

### ISSUE THREAD

**Issue by leubao** [zoujingli/wechat-php-sdk#14]
代码如下，加入WechatPay.php 中，谢谢
/**
     *  Author: zhoujing 2017-02-16
     *  创建刷卡支付参数包
     *  @param string $prepay_id
     *  @return array
     */
    public function createMicroPay($auth_code,$out_trade_no,$total_fee,$body,$goods_tag = null){
        $postdata = array(
            "appid"            => $this->appid,
            "mch_id"           => $this->mch_id,
            "body"             => $body,
            "out_trade_no"     => $out_trade_no,
            "total_fee"        => $total_fee,
            "auth_code"        => $auth_code,
            "spbill_create_ip" => Tools::getAddress()
        );
        empty($goods_tag) || $postdata['goods_tag'] = $goods_tag;
        $result = $this->postXml($postdata, self::MCH_BASE_URL . '/pay/micropay');
        $json = Tools::xml2arr($result);
        if (!empty($json) && false === $this->_parseResult($json)) {
            return false;
        }
        return $json;
    }

**Comment by zoujingli** [comment]
已经添加，dev-master 分支
