### ISSUE TITLE
在CLI模式下access_token会出错

### ISSUE THREAD

**Issue by shenfeng07** [zoujingli/wechat-php-sdk#15]
if (!$this->access_token && !$this->getAccessToken()) {
            return false;
 }
在CLI模式下，$this->access_token在第一次获取后会一直存在，导致过期后依然使用过期的access_token。
我在使用think-queue的work模式处理模板消息时发现过一段时间后一直会出现access_token错误。

**Comment by zoujingli** [comment]
SDK方法自带重置token，如果你是要自己使用token，而不是调用SDK内置方法，那Token是可能会过期的

**Comment by zoujingli** [comment]
还有一种情况，如果是cli模式，建议使用new 去实例对象。如果是使用单例模式，token会在SDK中属性中，就不会再重新获取新的token。所有如果是cli模式，在使用的时候$sdk = new SDK(config);

**Comment by zoujingli** [comment]
还可以在使用前，
```
$user  = & load_wechat("User");
$user -> $access_token = ''; 
// 去除实例对象中的token，让之在方法执行中重新读取token
$user->方法（）；
```
