### ISSUE TITLE
素材上传的代码这段貌似会产生BUG

### ISSUE THREAD

**Issue by moufer** [zoujingli/wechat-php-sdk#30]
https://github.com/zoujingli/wechat-php-sdk/blob/7869490b99e648d40a5a5169cc0469dccb8e8b0a/Wechat/WechatMedia.php#L190

`        list($cache_file, $media_content) = ['', base64_decode($data['media'])];
        if (!empty($media_content) && ($cache_file = Cache::file($media_content))) {
            $data['media'] = "@{$cache_file}";
        }`

php7.0下测试，$data['media']='@/www/abc.jpg'时而不是base64形式的图片时，$media_content这个变量始终会有值,一串乱码，从而下面的条件判断成立，$cache_file=xxxxxxxx.mp4，造成微信之中返回media data missing hint，应该判断下base64_decode($data['media'])是不是base64再base64_decode

**Comment by zoujingli** [comment]
有提交一个版本，试试 dev-master

**Comment by moufer** [comment]
没问题了
