### ISSUE TITLE
今天收到“微信支付接口安全提醒通知”，sdk是否要禁止外部引用xml的代码？

### ISSUE THREAD

**Issue by moufer** [zoujingli/wechat-php-sdk#31]
https://github.com/zoujingli/wechat-php-sdk/blob/ccd6533775d2b8c4e2fe95cc04cefa3eef9fc095/Wechat/WechatPay.php#L211

前后加上
$bPreviousValue = libxml_disable_entity_loader(true);
和
libxml_disable_entity_loader($bPreviousValue);

另外还有Tools类里xml2arr函数

**Comment by zoujingli** [comment]
其实这个意义不大的
一、有签名认证
二、接口注入也难以找到
