### ISSUE TITLE
Tools::arr2xml中局部函数_data_to_xml不兼容PHP5.3

### ISSUE THREAD

**Issue by firebear** [zoujingli/wechat-php-sdk#7]
wechat-php-sdk/Wechat/Lib/Tools.php
改为这样才OK了：
`    static protected function _data_to_xml($data, $item = 'item', $id = 'id', $content = '') {...}
`
`    static public function arr2xml($data, $root = 'xml', $item = 'item', $id = 'id') {
        return "<{$root}>" . self::_data_to_xml($data, $item, $id) . "</{$root}>";
    }
`
测试环境：新浪SAE PHP5.3

**Comment by zoujingli** [comment]
谢谢反馈，问题已经解决，v1.3.4
