### ISSUE TITLE
WechatPay的getPrepayId支持不了微信扫码支付模式1

### ISSUE THREAD

**Issue by firebear** [zoujingli/wechat-php-sdk#8]
微信的扫码支付模式1，trade_type应该设置为NATIVE，但是按目前的实现，WechatPay的getPrepayId将返回二维码链接，响应给微信的扫码通知回调后，会导致微信扫里报“package info not match special pay url”错误。
代码改成这样就可以通过。
![image](https://cloud.githubusercontent.com/assets/718573/20951478/e8b39f46-bc60-11e6-9051-fb99b252e6f1.png)
不太熟微信支付，微信扫码支付模式1这样可以走通，但是这么改可能有其他情况不兼容。  @Anyon 你看一下

**Comment by zoujingli** [comment]
已增加新接口，请查看支付文档，谢谢！
